name: The Praxis Program
#baseurl: /praxis
# markdown: redcarpet
highlighter: rouge
exclude: ['_sass', 'bower_components', 'node_modules', 'Rakefile', 'README.md', 'config.rb', '_config.yml', 'Gemfile', 'Gemfile.lock', '_settings.yml', 'plugins']

domain: praxis.scholarslab.org
title: The Praxis Program
author: Scholars' Lab
email: praxis@collab.itc.virginia.edu
basefeed: http://www.scholarslab.org
permalink: pretty
plugins:
  - jekyll-sitemap
collections:
  resources:
    output: true
    permalink: /:collection/:name/
  sessions:
    output: true
    permalink: /:collection/:name/
