#+TITLE: Notes from class meeting Oct 8
#+AUTHOR: James P. Ascher
#+EMAIL: jpa4q@virginia.edu

* Present at the meeting
  Scott, Lydia, Bremen, Ethan, Eric, Ammon, Purdom, Laura (Purdom's sister), James, Gillete, Clair (not participating)
  began at 9:10 am

* Check-in
** P: Jekyll check-in, is everyone getting it?                       :Purdom:
** Catch-up for Purdom who wasn't here last week
*** Bremen: discusses overlap and conversations                      :Bremen:
*** Gillete: into Lydia's Gogo plans                                :Gillete:
*** Lydia: we have broad areas of convergence, including ethics       :Lydia:
*** James: some nonsense about "the carp in the stone"                :James:
*** Gillete: stressors, overlap between categories and Scott relates :Gillete:
*** Lydia: perhaps we should all form small groups to discuss articles with directed reading; Bremen, Purdom, Scott concur :Lydia:
*** G: interested in how do we distill information from the meeting? Who will post notes? :Gillete:
*** P: keep it loose and self-appoint when we do meet; keep slab staff in the loop; print tiara for everyone? suggests that she will post instructions? :Purdom:
*** S: says they're there already                                     :Scott:
*** TODO P: will review and decide if something needs to be added    :Purdom:
    SCHEDULED: <2015-10-09 Fri>
*** S: explains how the image folders work, Ethan's, Scott's, or James's post to put images :Scott:
*** J asks about the plugins on github, S explains the nature of the plugins on the website (various ones supported by github, some are compiled locally) :James:Scott:

* Case studies
** B: we were still hashing things out                               :Bremen:
** J: posted a memo of his case study                                 :James:
** S: reading more about time perception and people with terminal illnesses, "entering a world with no future" :Scott:
*** Three conclusions: no future, no ability to plan, disjunction between planning with friends while healthy :Scott:
*** many didn't want information about the prognosis, but the sense of the lack of future remained :Scott:
*** friends remained future oriented, so they felt outside of time, no idea how much longer they'll last :Scott:
**** Discussion
**** La: nurse for oncology, everything rings true to her experience  :Laura:
**** A: children function like this too, and "a sec" is very confusing to them because it's not a second, but could be 20 minutes which feels longer for children :Ammon:
**** S: they only talked to people over 18 in the study; A: Alzheimer's? :Scott:Ammon:
*** talking about caregivers, asking for help: felt like *taking time* from someone else, so if people *gave time* it felt more comfortable for the patient :Scott:
*** S: asking about the gift and the philosophy of the gift; but the language seems to be one of the /economics of affect/ :Scott:
**** P: we're future oriented, so being terminally ill crystallizes: time shifts from a vague possibility to something that *IS* :Purdom:
**** B: thinking about policing, parallel: time as trust; how people understand their obligations to others; connects to S in feeling out of time with others, with a chronic instability of life it becomes complicated and important for representation; can we understand how people are in time :Bremen:
**** S: compare people with term. ill with people in prison: "imprisoned by the illness" or "Locked in"; monasteries might connect to imprisoned people :Scott:
**** P: when someone is ill in the hospital, there is so much alone time in a room :Purdom:
**** La: "literally an 8 year old and they are in a room smaller than this for 45 days" the kind only has a few visitors; being specific about the time on the clock because "she is aware of how precious those moments are" and wants to help make time pass faster for the kids; teenagers are more difficult because they need entertainment :Laura:
**** S: is the order and structure the same?                          :Scott:
**** La: various things can impact the day, one can hope to have it consistent, but may-or-may-not be :Laura:
**** S: _icon set_ set of small drawings for regular events throughout the day to be oriented, you can see the structure of the day; make an icon set for a normal person and look for repetitions, do the same for different types of illnesses; is it still repetition or pure chaos? :Scott:
**** Er: tying in several comment: medieval- 2 groups occupied: younger nobility or minor English King who retired; different conceptions of time- same as nurses and teachers and different people; the icon set may also communicate between teachers and students; different groups occupying the same space :Eric:
** Ly: "Towards an Ecology of Time..." will post, broadly about music as a way to bind us into time; :Lydia:
*** rhythm is what binds us; categorizes sounds to give a rhythm;     :Lydia:
*** Bachelor (?) philosopher: social cohesion is people able to think at the same time; :Lydia:
*** when something is out of time or out of tune; we enact agency by choosing how to cohabitate in time; :Lydia:
*** grandmother had cancer, but was not told because it was inoperable and she didn't want to know; she knew something was wrong, but never *knew*; :Lydia:
*** there is a way that time is shortened or prolonged by awareness of illness :Lydia:
**** Discussion
**** G: aunt had pain and it turned out she had cancer; once it became clear her body couldn't handle it, she went right into hospice :Gillete:
**** A: mother's passing, she felt that she had way-extended her time already :Ammon:
**** P: understandings of time while others are dying around you connects to B's topic of crisis time; really little when AIDS hit Jacksonville, many men died very quickly, not much effect on them as children, but mother has a different relationship to time :Purdom:
**** A: grandparents 80s and 90s, amazed at they are still alive and enjoying it in contrast to those who are waiting :Ammon:
**** G: All the King's Men: time is a force that operates of its own accord- an active and literal force; A: a gravity?; G: yeah, pushing down on you :Gillete:
**** P: embodied time versus time as an external force               :Purdom:
**** S: clocks are interesting because they are an external measure of time, but if you actually perceive it in a radically different way; technologies of objective time can be so affectively changed that they are no longer objective time keepers :Scott:
**** G: what do drugs do to time? e.g. once on "dilotin" time went fast :Gillete:
**** P: on morphine, timed with the Price is Right: he wanted colors to meditate on? :Purdom:
**** La: some people feel like illness is an attack on their time because the kid is sick, others support; 10 year olds don't have a concept of death; proactive families vs. embittered families: that week can feel very differently given the emotional aspect; some families are demanding, others wait patiently, but changes how time feels :Laura:
**** B: resilience and response to a brain aneurysm; she responded well and it effected the progression of the illness; _resilience_ seems to be a key term :Bremen:
** J: some nonsense on note-taking; observes that it can show someone's point of view in a profound way :James:
*** Ly: horrified that someone will see notes after someone's death; people will go through stuff after death, she'll be bugged; she hides books with marginalia because she's worried people will know how her brain works; other professors will share notes :Lydia:
*** P: mark of a person in time: notes in books; some people are good personal-archivists; Salman Rushdie's computers, did a case study about his papers, became very intimate with how his brain worked; what he remembered and what he forgot about: revealed so much of his system of thought; the notes become a *pace* in time and reviewing the notes people die again :Purdom:
*** Et: notes persist way longer than the person does; anticipation is part of them; Kafka, he's like not going to burn everything- nothing he can do; "*the future is really public*" :Ethan:
*** P: _Immortality_: Beethoven is trying to form his own, but in conflict with; oh wait it's Goethe, but his love interest has a different interest; follows into the afterlife and Goethe picks a different representation :Purdom:
*** B: ethnography about Young People in Philadelphia running from the law _On the Run_; G: wants to talk about it with B; really controversial as to whether or not it's true; all the ways that people destroy their archives to avoid the law; ways that people are forced to lie to loved ones to protect them; material stuff becomes really important in the way that relationships are maintained; "*the future is very public*" :Bremen:Gillete:
** Et: objects and how we consume things in his drawings--orals!--brought in Marx _Capital_ specific technical definition of labor time: value of commodity produced by this labor time, as exchange values all commodities are "definite quantities of congealed labor time" :Ethan:
*** J: labor time congealed into ethics                               :James:
*** Et: limits of thinking about commodities this way; a jar of peanut butter, so many hours of work; what are the limits of E's labor :Ethan:
*** Ly: labor time buys stuff and labor time makes stuff, it's hard to trace; capitalism in music, cost $0.99, what is the labor that went into this; a mass market system hides this; what are you buying? :Lydia:
*** G: thinking of people as commodities- how does labor go into that? enslavement? athletes? putting in labor time and getting so much less out of it; how does that work when its people? Or when people are being exploited? :Gillete:
*** B: efficiency experiments, time-motion studies; how workers relate :Bremen:
*** La: looking at wrongful death suits, younger people are viewed as more valuable commodity; families get more money in wrongful death for younger people :Laura:
*** G: slavery in America, people were valued very highly as was their labor; the enslavers wouldn't represent that to the person who was enslaved; if someone got injured :Gillete:
*** La: language of worth and value becomes conflicted in this occasion of slavery :Laura:
*** P: difficult article on doctors who are physicians to enslaved peoples... posting if possible?; more likely for a blacksmith, but less likely for a child; grappling with _worth_ vs. _value_ :Purdom:
*** G: more concerned as we get closer to the civil war, they become more valuable :Gillete:
*** TODO Ly: will blog?: Lomax Archives online, recording in the 1920s of people around the world; recording African American men in prisons, songs available online for free; copyright owned by Lomax family, the slaves aren't even named (prison laborers?); there's another archive of the Lomax notes, of its time, but doesn't get the creators of the songs; copyright is meant to privilege the author: systematic flaw; commodification of actual labor; J: ethical audits of archives; Ly: look at Lomax? fun to fiddle with, but might not be ethical- ethics of a database, commodity, enslavement, Marxist :Lydia:
** G: congealed labor and experiences: going to a fair- ride a Ferris wheel, what goes on to make that happen? time to set the fair up? what were people paid before you arrived? what is the value relation :Gillete:
*** S: Hardt and Negri model in _Empire_ movement from industrial to production of affect; their example is flight-attendants: you use the right smile and manners, that's what you're paid for; harnessing of your own emotional and physical being; carnival or the fair: what are the actual labor practices that go into it; Disney employees are docked for being glum :Scott:
*** P: everyone in the park has to be a "imagineer" which is documented in a book, there exists an underground path of space out of time in Disney world; you don't have to follow protocol :Purdom:
*** TODO G: article about Williamsburg, will find and post; B: who wrote it? was it a prof here?; G: Marlon Ross made me read it; P: would love to read it :Gillete:
*** P: lord mayor of the Renaissance fair, lord mayor toad, trying to connect with the kid; representation at the fair- how it's strange; *dino time* :Purdom:
*** Ly: it's like Futurama the 90s people look like 20s people        :Lydia:

* What are we working on this week?
** Continuing on Inktober
** Continuing to develop case studies
** TODO All: seeking areas of convergence, start sketching out representations of time? super-compelling, what does time sound or act like? :All:
   DEADLINE: <2015-10-15 Thu>
** TODO Purdom: will prepare Makespace activity for next week to help continue to think :Purdom:
   DEADLINE: <2015-10-15 Thu>
** TODO All: come in with something you *will* share with the group which you have also posted :All:
   DEADLINE: <2015-10-15 Thu>

* ends at 10:45
